name: Client CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: client-ci
  cancel-in-progress: true

jobs:
  client-ci:
    name: CI Pipeline for Client
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: Client/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build Client
        run: npm run build
