name: Client CD

on:
  workflow_run:
    workflows:
      - Client CI
    types:
      - completed

permissions:
  contents: read

concurrency:
  group: client-cd
  cancel-in-progress: true

jobs:
  client-cd:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'

    name: CD Pipeline for Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Client

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build-Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./Client
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-code-client:latest
            ${{ secrets.DOCKER_USERNAME }}/ai-code-client:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - run: npm install -g vercel@latest

      - name: Pull Project
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Trigger Vercel Deployment
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
