name: Client CI | AI Code Reviewer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client-ci:
    name: CI Pipeline for Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup-Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependancy-path: Client/package-lock.json

      - name: Install dependancies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build Client
        run: npm run build
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./Client
          push: false
          tags: ai-code-server:latest
